apiVersion: apps/v1
kind: Deployment
metadata:
  name: dl-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dl-api
  template:
    metadata:
      labels:
        app: dl-api
    spec:
      containers:
      - name: dl-api
        image: europe-west1-docker.pkg.dev/deeplearning-project-495018/dl-repo/dl-api:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000