apiVersion: apps/v1
kind: Deployment
metadata:
  name: dl-api-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dl-api-prod
  template:
    metadata:
      labels:
        app: dl-api-prod
    spec:
      containers:
      - name: dl-api-prod
        image: europe-west1-docker.pkg.dev/deeplearning-project-495018/dl-repo/dl-api-prod:v4
        ports:
        - containerPort: 8000